name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish-core:
    name: Publish edgepulse_core to pub.dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Publish
        working-directory: packages/edgepulse_core
        run: |
          dart pub get
          dart pub publish --force

  publish-cli:
    name: Publish edgepulse_cli to pub.dev
    runs-on: ubuntu-latest
    needs: [publish-core]
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Publish
        working-directory: packages/edgepulse_cli
        run: |
          dart pub get
          dart pub publish --force
